language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails3.gemfile
script: "bundle exec rake coverage"
notifications:
  email:
    - support@travellink.com.au
