language: ruby
rvm:
  - 2.2
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
script: "bundle exec rake spec"
notifications:
  email:
    - support@travellink.com.au
  flowdock:
    secure: A0Fr9j0kvKPEWuPbJu/DPMYPvx98UI8k43adKN9UjTB6FRVAQM3kXmKJIL3A495scc2Civrg2KHDkbwNwVThY+HdLeU7q71Bm6obP6ZkCe43MIoc9NiVJymCNguku6+tLEyusdWIceFiBW7P5p/sU1QU66GFj1t4wNTpVq9A4Kw=
sudo: false
cache: bundler
